// Code generated by tygo. DO NOT EDIT.

//////////
// source: view.go
/*
Package view holds the pane's DTOs and is the source of web/src/api/types.gen.ts.
Secrets stay out by construction: no type here has a field for a
subscription URL, credential, server address or token.
*/

export interface Status {
  version: string;
  started: string;
  upstream: string; // host only
  primary?: NodeRef;
  nodes: number /* int */;
  usable: number /* int */; // breaker closed
  sessions: Session[];
  limits: Limits;
}
/**
 * Limits are the control settings the pane draws against.
 */
export interface Limits {
  bufferMinSeconds: number /* float64 */;
  readAheadSeconds: number /* float64 */;
}
export interface NodeRef {
  id: string;
  name: string;
}
export interface Session {
  key: string;
  media: NodeRef;
  streams: number /* int */; // open player connections
  bitrateMbps: number /* float64 */;
  bufferSeconds: number /* float64 */;
  liveMbps: number /* float64 */;
  safeMbps: number /* float64 */; // what its media node keeps to, see Choice
  needMbps: number /* float64 */; // what it needs over the horizon at its buffer
  failovers: number /* int */;
  started: string;
  item?: Item; // unknown until a player fetches the item's details
}
/**
 * Item is what a session plays, as the player's own request for the item's
 * details showed it.
 */
export interface Item {
  id: string;
  type: string; // Movie, Episode, Audio, ...
  name: string;
  seriesName?: string;
  season?: number /* int */;
  episode?: number /* int */;
  year?: number /* int */;
  image: boolean; // served at /api/v1/items/{id}/image
}
/**
 * SessionDetail is a session and the choice its next step faces. Once the
 * session ends, only its events remain.
 */
export interface SessionDetail {
  session?: Session;
  verdict?: Verdict;
  choices: Choice[]; // staying first, then moves from best
  events: Event[];
}
/**
 * Verdict is what the next step does: stay, or switch To.
 */
export interface Verdict {
  to?: NodeRef;
  reason: string;
}
/**
 * Choice is one node as the session's step judges it: staying on the media
 * node, or switching to another, which delivers nothing for its gap. It
 * meets the target when it is known and SafeMbps covers NeedMbps.
 */
export interface Choice {
  node: NodeRef;
  role: string; // media or ""
  gapSeconds: number /* float64 */;
  known: boolean; // enough recent samples to trust
  safeMbps: number /* float64 */; // its rate now, one spread under the typical
  needMbps: number /* float64 */; // to keep the buffer over its low mark, after the gap
  rateMbps: Estimate; // as judged: the media node's includes the stream's samples
}
/**
 * Estimate summarizes a node's measurements: their typical value and the
 * 90% range of one sample, and how many samples' worth of evidence remain
 * after fade-out.
 */
export interface Estimate {
  measured: boolean;
  mean: number /* float64 */;
  low: number /* float64 */;
  high: number /* float64 */;
  evidence: number /* float64 */;
}
export interface Node {
  id: string;
  name: string;
  protocol: string;
  provider: string;
  rttMs: Estimate;
  rateMbps: Estimate;
  breakerOpen: boolean;
  openUntil?: string;
  roles: string[]; // primary, media, pinned
}
export interface NodeDetail extends Node {
  samples: Sample[];
}
export interface Sample {
  time: string;
  kind: string;
  mbps: number /* float64 */;
  ttfbMs: number /* float64 */;
  error: string;
}
export interface Event {
  time: string;
  level: string;
  message: string;
  attrs: { [key: string]: string};
}
