// Code generated by tygo. DO NOT EDIT.

//////////
// source: view.go
/*
Package view holds the pane's DTOs and is the source of web/src/api/types.gen.ts.
Secrets stay out by construction: no type here has a field for a
subscription URL, credential, server address or token.
*/

export interface Status {
  version: string;
  started: string;
  upstream: string; // host only
  primary?: NodeRef;
  nodes: number /* int */;
  usable: number /* int */; // breaker closed
  measured: number /* int */; // usable, with a rate measured
  testing?: NodeRef;
  testsPaused?: string; // until, after the server refused a test
  sessions: Session[]; // playing, oldest first
  recent: Session[]; // ended within a day, newest first
  limits: Limits;
}
/**
 * Limits are the control settings the pane draws against.
 */
export interface Limits {
  bufferMinSeconds: number /* float64 */;
  readAheadSeconds: number /* float64 */;
}
export interface NodeRef {
  id: string;
  name: string;
}
/**
 * Session is one playback as of its controller's last step, or as it ended.
 */
export interface Session {
  key: string;
  state: string; // starting, ok, risk, low, idle or ended
  media: NodeRef;
  players: number /* int */; // open player connections
  bitrateMbps: number /* float64 */;
  bufferSeconds: number /* float64 */; // read-ahead plus a lower bound on the player's own
  fetchedMbps: number /* float64 */; // read from upstream over the last step
  nodeMbps: number /* float64 */; // the media node's average rate, 0 if not measured
  failovers: number /* int */;
  tests: number /* int */;
  lowSeconds: number /* float64 */; // under the low mark, once first over it
  started: string;
  ended?: string;
  item?: Item; // unknown until a player fetches the item's details
}
/**
 * Item is what a session plays, as the player's own request for the item's
 * details showed it.
 */
export interface Item {
  id: string;
  type: string; // Movie, Episode, Audio, ...
  name: string;
  seriesName?: string;
  season?: number /* int */;
  episode?: number /* int */;
  year?: number /* int */;
  image: boolean; // served at /api/v1/items/{id}/image
}
/**
 * SessionDetail is a session with its recent steps. Once the session has
 * been forgotten, only its events remain.
 */
export interface SessionDetail {
  session?: Session;
  history: Point[]; // oldest first, up to 10 min
  events: Event[];
}
/**
 * Point is one step of a session.
 */
export interface Point {
  at: string;
  buffer: number /* float64 */; // s
  mbps: number /* float64 */; // fetched
}
/**
 * Estimate is a moving average of a node's measurements.
 */
export interface Estimate {
  measured: boolean;
  mean: number /* float64 */;
}
export interface Node {
  id: string;
  name: string;
  protocol: string;
  provider: string;
  rttMs: Estimate;
  rateMbps: Estimate;
  sampled?: string; // its last rate sample
  breakerOpen: boolean;
  openUntil?: string;
  roles: string[]; // primary, media, pinned
}
export interface NodeDetail extends Node {
  samples: Sample[];
}
export interface Sample {
  time: string;
  kind: string;
  mbps: number /* float64 */;
  ttfbMs: number /* float64 */;
  error: string;
}
export interface Event {
  time: string;
  level: string;
  message: string;
  attrs: { [key: string]: string};
}
