/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AppRouteImport } from './routes/_app'
import { Route as AppIndexRouteImport } from './routes/_app/index'
import { Route as AppEventsRouteImport } from './routes/_app/events'
import { Route as AppNodesIndexRouteImport } from './routes/_app/nodes.index'
import { Route as AppNodesIdRouteImport } from './routes/_app/nodes.$id'
import { Route as AppSessionsIndexRouteImport } from './routes/_app/sessions.index'
import { Route as AppSessionsKeyRouteImport } from './routes/_app/sessions.$key'

const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const AppEventsRoute = AppEventsRouteImport.update({
  id: '/events',
  path: '/events',
  getParentRoute: () => AppRoute,
} as any)
const AppNodesIndexRoute = AppNodesIndexRouteImport.update({
  id: '/nodes/',
  path: '/nodes/',
  getParentRoute: () => AppRoute,
} as any)
const AppNodesIdRoute = AppNodesIdRouteImport.update({
  id: '/nodes/$id',
  path: '/nodes/$id',
  getParentRoute: () => AppRoute,
} as any)
const AppSessionsIndexRoute = AppSessionsIndexRouteImport.update({
  id: '/sessions/',
  path: '/sessions/',
  getParentRoute: () => AppRoute,
} as any)
const AppSessionsKeyRoute = AppSessionsKeyRouteImport.update({
  id: '/sessions/$key',
  path: '/sessions/$key',
  getParentRoute: () => AppRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof AppIndexRoute
  '/events': typeof AppEventsRoute
  '/nodes/$id': typeof AppNodesIdRoute
  '/sessions/$key': typeof AppSessionsKeyRoute
  '/nodes/': typeof AppNodesIndexRoute
  '/sessions/': typeof AppSessionsIndexRoute
}
export interface FileRoutesByTo {
  '/events': typeof AppEventsRoute
  '/': typeof AppIndexRoute
  '/nodes/$id': typeof AppNodesIdRoute
  '/sessions/$key': typeof AppSessionsKeyRoute
  '/nodes': typeof AppNodesIndexRoute
  '/sessions': typeof AppSessionsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_app': typeof AppRouteWithChildren
  '/_app/events': typeof AppEventsRoute
  '/_app/': typeof AppIndexRoute
  '/_app/nodes/$id': typeof AppNodesIdRoute
  '/_app/sessions/$key': typeof AppSessionsKeyRoute
  '/_app/nodes/': typeof AppNodesIndexRoute
  '/_app/sessions/': typeof AppSessionsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    '/' | '/events' | '/nodes/$id' | '/sessions/$key' | '/nodes/' | '/sessions/'
  fileRoutesByTo: FileRoutesByTo
  to: '/events' | '/' | '/nodes/$id' | '/sessions/$key' | '/nodes' | '/sessions'
  id:
    | '__root__'
    | '/_app'
    | '/_app/events'
    | '/_app/'
    | '/_app/nodes/$id'
    | '/_app/sessions/$key'
    | '/_app/nodes/'
    | '/_app/sessions/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AppRoute: typeof AppRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/': {
      id: '/_app/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/events': {
      id: '/_app/events'
      path: '/events'
      fullPath: '/events'
      preLoaderRoute: typeof AppEventsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/nodes/': {
      id: '/_app/nodes/'
      path: '/nodes'
      fullPath: '/nodes/'
      preLoaderRoute: typeof AppNodesIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/nodes/$id': {
      id: '/_app/nodes/$id'
      path: '/nodes/$id'
      fullPath: '/nodes/$id'
      preLoaderRoute: typeof AppNodesIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/sessions/': {
      id: '/_app/sessions/'
      path: '/sessions'
      fullPath: '/sessions/'
      preLoaderRoute: typeof AppSessionsIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/sessions/$key': {
      id: '/_app/sessions/$key'
      path: '/sessions/$key'
      fullPath: '/sessions/$key'
      preLoaderRoute: typeof AppSessionsKeyRouteImport
      parentRoute: typeof AppRoute
    }
  }
}

interface AppRouteChildren {
  AppEventsRoute: typeof AppEventsRoute
  AppIndexRoute: typeof AppIndexRoute
  AppNodesIdRoute: typeof AppNodesIdRoute
  AppSessionsKeyRoute: typeof AppSessionsKeyRoute
  AppNodesIndexRoute: typeof AppNodesIndexRoute
  AppSessionsIndexRoute: typeof AppSessionsIndexRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppEventsRoute: AppEventsRoute,
  AppIndexRoute: AppIndexRoute,
  AppNodesIdRoute: AppNodesIdRoute,
  AppSessionsKeyRoute: AppSessionsKeyRoute,
  AppNodesIndexRoute: AppNodesIndexRoute,
  AppSessionsIndexRoute: AppSessionsIndexRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AppRoute: AppRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
